/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import jnafilechooser.api.JnaFileChooser;
import model.Nelayan; 
import model.User;   
import model.enums.StatusNelayan;   
import controller.LaporanPengaduanController;
import dao.LaporanPengaduanDAO;
import java.io.File;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jnafilechooser.api.JnaFileChooser;
import model.Nelayan;
import model.User;
import model.enums.JenisPengaduan;
import model.enums.StatusNelayan;
import model.LaporanPengaduan;
import model.enums.JenisPengaduan;
/**
 *
 * @author rfebr
 */
public class FormLaporanPengaduan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLaporanPengaduan.class.getName());
    private String selectedImagePath;  
    private User currentUser;
    private final LaporanPengaduanController controller = new LaporanPengaduanController();
    private final LaporanPengaduanDAO dao = new LaporanPengaduanDAO();
    private final String DRIVE_FOLDER_ID = "1deXe45uwk7tlcbgRs1PXDjQmZVaHIgJp";
    private List<LaporanPengaduan> currentLaporanList;


    /**
     * Creates new form pengaduanPage
     */
    public FormLaporanPengaduan(User user) { 
        initComponents();
        this.currentUser = user; 
        lblPreview.setVisible(false);
        setLocationRelativeTo(null);
        setTitle("Laporan Pengaduan - " + user.getNama());
        drpJenisPengaduan.removeAllItems();
        drpJenisPengaduan.addItem("Pilih Jenis Pengaduan"); 
        for (JenisPengaduan jenis : JenisPengaduan.values()) {
            drpJenisPengaduan.addItem(jenis.toString()); 
        }
        loadTableData();
    }
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tblPengaduan.getModel();
        model.setRowCount(0);
        this.currentLaporanList = dao.findByUserId(currentUser.getUserId());
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        if (this.currentLaporanList != null) { 
            for (LaporanPengaduan lap : this.currentLaporanList) { 
                model.addRow(new Object[]{
                    lap.getTanggalPengaduan().format(formatter),
                    lap.getJenisPengaduan(), 
                    lap.getDeskripsi(),
                    lap.getTitikKoordinat(),
                    lap.getStatusPengaduan(), 
                    lap.getCatatan()
                });
            }
        }
    }
    private void clearForm() {
            drpJenisPengaduan.setSelectedIndex(0);
            txtDeskripsi.setText("");
            txtKoordinat.setText("");
            selectedImagePath = null;
            lblPreview.setVisible(false);
            lblPreview.setText("");
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropKategori1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPengaduan = new javax.swing.JTable();
        btnUpload = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblPreview = new javax.swing.JLabel();
        btnKoordinat = new javax.swing.JButton();
        txtKoordinat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        drpJenisPengaduan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTambahPengaduan = new javax.swing.JButton();
        btnHapusPengaduan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();

        dropKategori1.setForeground(new java.awt.Color(0, 51, 102));
        dropKategori1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropKategori1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropKategori1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPengaduan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblPengaduan.setForeground(new java.awt.Color(0, 51, 102));
        tblPengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal Pengaduan", "Jenis Pengaduan", "Deskripsi", "Titik Koordinat", "Status", "Catatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPengaduan.setColumnSelectionAllowed(true);
        tblPengaduan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPengaduan);
        tblPengaduan.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 630, 140));

        btnUpload.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnUpload.setForeground(new java.awt.Color(0, 51, 102));
        btnUpload.setText("Upload");
        btnUpload.setFocusPainted(false);
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 255, 90, 30));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bukti Foto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        lblPreview.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblPreview.setForeground(new java.awt.Color(242, 242, 242));
        lblPreview.setText("jLabel7");
        getContentPane().add(lblPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        btnKoordinat.setBackground(new java.awt.Color(153, 153, 153));
        btnKoordinat.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnKoordinat.setForeground(new java.awt.Color(255, 255, 255));
        btnKoordinat.setText("Ubah");
        btnKoordinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKoordinatActionPerformed(evt);
            }
        });
        getContentPane().add(btnKoordinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 80, 30));

        txtKoordinat.setEditable(false);
        txtKoordinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKoordinatActionPerformed(evt);
            }
        });
        getContentPane().add(txtKoordinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 210, 30));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titik Koordinat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 290, 80));

        drpJenisPengaduan.setForeground(new java.awt.Color(0, 51, 102));
        drpJenisPengaduan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drpJenisPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpJenisPengaduanActionPerformed(evt);
            }
        });
        getContentPane().add(drpJenisPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 158, 290, 30));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jenis Pengaduan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Deskripsi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        btnTambahPengaduan.setBackground(new java.awt.Color(52, 99, 146));
        btnTambahPengaduan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTambahPengaduan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengaduan.setText("Tambah");
        btnTambahPengaduan.setBorderPainted(false);
        btnTambahPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPengaduanActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 90, 30));

        btnHapusPengaduan.setBackground(new java.awt.Color(153, 0, 0));
        btnHapusPengaduan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnHapusPengaduan.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusPengaduan.setText("Hapus");
        btnHapusPengaduan.setBorderPainted(false);
        btnHapusPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPengaduanActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapusPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 90, 30));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Laporan Pengaduan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo Dark.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 720, 400));

        btnKembali.setBackground(new java.awt.Color(52, 99, 146));
        btnKembali.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.setBorderPainted(false);
        btnKembali.setFocusable(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
          JnaFileChooser fileChooser = new JnaFileChooser();
    
    fileChooser.setTitle("Pilih Foto Kapal");
    
    fileChooser.addFilter("Gambar (*.jpg, *.png, *.jpeg)", "jpg", "png", "jpeg");
    
    boolean result = fileChooser.showOpenDialog(this);

   if (result) { 
            File selectedFile = fileChooser.getSelectedFile();
            
            if (selectedFile != null) {
                
                
                long fileSizeInBytes = selectedFile.length();
                long fileSizeInMB = fileSizeInBytes / (1024 * 1024);
                
                long MAX_FILE_SIZE_MB = 5; 

                if (fileSizeInMB > MAX_FILE_SIZE_MB) {
                    JOptionPane.showMessageDialog(this, 
                        "Ukuran file terlalu besar (" + fileSizeInMB + " MB).\nBatas maksimal adalah " + MAX_FILE_SIZE_MB + " MB.", 
                        "Error Ukuran File", 
                        JOptionPane.ERROR_MESSAGE);
                    
                    selectedImagePath = null;
                    lblPreview.setVisible(false);
                    return; 
                }

                selectedImagePath = selectedFile.getAbsolutePath();
                lblPreview.setText("File terpilih: " + selectedFile.getName());
                lblPreview.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnHapusPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPengaduanActionPerformed
           
        int selectedRow = tblPengaduan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih laporan yang ingin dihapus dari tabel.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        

        if (this.currentLaporanList == null || this.currentLaporanList.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Data laporan tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        LaporanPengaduan laporan = this.currentLaporanList.get(selectedRow);
        
        int response = JOptionPane.showConfirmDialog(
                this, 
                "Apakah Anda yakin ingin menghapus pengaduan ini?", 
                "Konfirmasi Hapus", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE
        );
        
        if (response == JOptionPane.YES_OPTION) {
            try {
                controller.hapusLaporanPengaduan(laporan);
                
                JOptionPane.showMessageDialog(this, "Laporan berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadTableData(); 
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_btnHapusPengaduanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
      if (this.currentUser instanceof Nelayan && 
            ((Nelayan) this.currentUser).getStatusNelayan() == StatusNelayan.Aktif) 
        {
            new MenuNelayan((Nelayan) this.currentUser).setVisible(true);
        } else {

            new MenuUser(this.currentUser).setVisible(true);
        }
        
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtKoordinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKoordinatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKoordinatActionPerformed

    private void btnKoordinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKoordinatActionPerformed
        // TODO add your handling code here:
            MapPicker mapPicker = new MapPicker(this, true);
    mapPicker.setVisible(true);
    
    if (mapPicker.getSelectedPosition() != null) {
        double lat = mapPicker.getSelectedPosition().getLatitude();
        double lon = mapPicker.getSelectedPosition().getLongitude();
        txtKoordinat.setText(String.format("%.6f,%.6f", lat, lon));
    }
    }//GEN-LAST:event_btnKoordinatActionPerformed

    private void btnTambahPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPengaduanActionPerformed
        if (drpJenisPengaduan.getSelectedIndex() <= 0) { 
             JOptionPane.showMessageDialog(this, "Silakan pilih jenis pengaduan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String jenisString = (String) drpJenisPengaduan.getSelectedItem();
        String deskripsi = txtDeskripsi.getText().trim();
        String koordinat = txtKoordinat.getText().trim();
        
        if (deskripsi.isEmpty() || koordinat.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Semua field teks harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (selectedImagePath == null || selectedImagePath.isBlank()) {
            JOptionPane.showMessageDialog(this, "Silakan upload foto bukti!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        JenisPengaduan jenisEnum = JenisPengaduan.valueOf(jenisString);

        LaporanPengaduan laporanBaru = new LaporanPengaduan();
        laporanBaru.setUser(this.currentUser); 
        laporanBaru.setJenisPengaduan(jenisEnum);
        laporanBaru.setDeskripsi(deskripsi);
        laporanBaru.setTitikKoordinat(koordinat);
        
        File fotoFile = new File(selectedImagePath);

        try {
            controller.buatLaporanBaru(laporanBaru, fotoFile, DRIVE_FOLDER_ID);
            
            JOptionPane.showMessageDialog(this, "Laporan pengaduan berhasil dikirim!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
            loadTableData();
            clearForm();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengirim laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            e.printStackTrace(); 
        }
    }//GEN-LAST:event_btnTambahPengaduanActionPerformed

    private void drpJenisPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpJenisPengaduanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_drpJenisPengaduanActionPerformed

    private void dropKategori1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropKategori1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dropKategori1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnHapusPengaduan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKoordinat;
    private javax.swing.JButton btnTambahPengaduan;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> dropKategori1;
    private javax.swing.JComboBox<String> drpJenisPengaduan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JTable tblPengaduan;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtKoordinat;
    // End of variables declaration//GEN-END:variables
}
