/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author rfebr
 */
public class LaporanPengaduan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LaporanPengaduan.class.getName());

    /**
     * Creates new form pengaduanPage
     */
    public LaporanPengaduan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJenisPengaduan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPengaduan = new javax.swing.JTable();
        btnTambahPengaduan = new javax.swing.JButton();
        btnHapusPengaduan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        txtKoordinat = new javax.swing.JTextField();
        btnKoordinat = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jenis Pengaduan:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titik Koordinat:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bukti Foto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));
        getContentPane().add(txtJenisPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 288, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Deskripsi:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        btnUpload.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpload.setForeground(new java.awt.Color(0, 51, 102));
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 90, 30));

        tblPengaduan.setForeground(new java.awt.Color(0, 51, 102));
        tblPengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal Pengaduan", "Jenis Pengaduan", "Deskripsi", "Titik Koordinat", "Status", "Catatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPengaduan.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblPengaduan);
        tblPengaduan.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 690, 180));

        btnTambahPengaduan.setBackground(new java.awt.Color(0, 51, 102));
        btnTambahPengaduan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambahPengaduan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahPengaduan.setText("Tambah");
        btnTambahPengaduan.setBorderPainted(false);
        getContentPane().add(btnTambahPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 90, 30));

        btnHapusPengaduan.setBackground(new java.awt.Color(153, 0, 0));
        btnHapusPengaduan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapusPengaduan.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusPengaduan.setText("Hapus");
        btnHapusPengaduan.setBorderPainted(false);
        btnHapusPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPengaduanActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapusPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 90, 30));

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 290, 100));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LAPORAN PENGADUAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        btnKembali.setBackground(new java.awt.Color(0, 51, 102));
        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.setBorderPainted(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 90, 30));

        txtKoordinat.setEditable(false);
        txtKoordinat.setPreferredSize(new java.awt.Dimension(64, 22));
        txtKoordinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKoordinatActionPerformed(evt);
            }
        });
        getContentPane().add(txtKoordinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 220, 30));

        btnKoordinat.setBackground(new java.awt.Color(0, 51, 102));
        btnKoordinat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKoordinat.setForeground(new java.awt.Color(255, 255, 255));
        btnKoordinat.setText("Ubah");
        btnKoordinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKoordinatActionPerformed(evt);
            }
        });
        getContentPane().add(btnKoordinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 80, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnHapusPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPengaduanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusPengaduanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        // if role = nelayan = menuNelayan else menuUser
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtKoordinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKoordinatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKoordinatActionPerformed

    private void btnKoordinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKoordinatActionPerformed
        // TODO add your handling code here:
            MapPicker mapPicker = new MapPicker(this, true);
    mapPicker.setVisible(true);
    
    if (mapPicker.getSelectedPosition() != null) {
        double lat = mapPicker.getSelectedPosition().getLatitude();
        double lon = mapPicker.getSelectedPosition().getLongitude();
        txtKoordinat.setText(String.format("%.6f,%.6f", lat, lon));
    }
    }//GEN-LAST:event_btnKoordinatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LaporanPengaduan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnHapusPengaduan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKoordinat;
    private javax.swing.JButton btnTambahPengaduan;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPengaduan;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtJenisPengaduan;
    private javax.swing.JTextField txtKoordinat;
    // End of variables declaration//GEN-END:variables
}
