/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.WilayahController;
import dao.WilayahTangkapDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.WilayahTangkap;

/**
 *
 * @author rfebr
 */
public class ManajamenWilayahTangkap extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManajamenWilayahTangkap.class.getName());

    /**
     * Creates new form manajemenAkunPegawai
     */
    public ManajamenWilayahTangkap() {
        initComponents();
        setLocationRelativeTo(null);
            loadTabel();

        
    }
private void kosongkanForm() {
    txtNamaWilayah.setText("");
    txtKoordinat.setText("");
}

private void loadTabel() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"Nama Wilayah Tangkap", "Titik Koordinat"}, 0
    );

    WilayahController controller = new WilayahController();
    for (WilayahTangkap w : controller.getAllWilayah()) {
        model.addRow(new Object[]{w.getNamaWilayah(), w.getKoordinat()});
    }

    tblWilayah.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNamaWilayah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKoordinat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWilayah = new javax.swing.JTable();
        btnEditWilayah = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnTambahWilayah = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Nama Wilayah Tangkap");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        txtNamaWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaWilayahActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaWilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 410, 30));

        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Titik Koordinat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        txtKoordinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKoordinatActionPerformed(evt);
            }
        });
        getContentPane().add(txtKoordinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 410, 30));

        tblWilayah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Wilayah Tangkap", "Titik Koordinat"
            }
        ));
        tblWilayah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWilayahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblWilayah);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 410, 170));

        btnEditWilayah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditWilayah.setForeground(new java.awt.Color(0, 102, 0));
        btnEditWilayah.setText("Edit");
        btnEditWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditWilayahActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditWilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 90, 30));

        btnKembali.setBackground(new java.awt.Color(0, 51, 102));
        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.setBorderPainted(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 100, 30));

        btnTambahWilayah.setBackground(new java.awt.Color(0, 51, 102));
        btnTambahWilayah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambahWilayah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahWilayah.setText("Tambah");
        btnTambahWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahWilayahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahWilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("MANAJEMEN WILAYAH TANGKAP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 500, 460));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaWilayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaWilayahActionPerformed

    private void txtKoordinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKoordinatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKoordinatActionPerformed

    private void btnEditWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditWilayahActionPerformed
        // TODO add your handling code here:
    int selectedRow = tblWilayah.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit!");
        return;
    }

    String namaLama = tblWilayah.getValueAt(selectedRow, 0).toString();

    WilayahTangkapDAO dao = new WilayahTangkapDAO();
    WilayahTangkap wilayah = dao.findByNama(namaLama); // nanti kita buat fungsi baru ini di DAO

    if (wilayah != null) {
        wilayah.setNamaWilayah(txtNamaWilayah.getText());
        wilayah.setKoordinat(txtKoordinat.getText());

        WilayahController controller = new WilayahController();
        controller.updateWilayah(wilayah);
        loadTabel();
        kosongkanForm();
    }
    }//GEN-LAST:event_btnEditWilayahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahWilayahActionPerformed
        // TODO add your handling code here:
            WilayahController controller = new WilayahController();
        controller.tambahWilayah(txtNamaWilayah.getText(), txtKoordinat.getText());
        loadTabel();
        kosongkanForm();
    }//GEN-LAST:event_btnTambahWilayahActionPerformed

    private void tblWilayahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWilayahMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblWilayah.getSelectedRow();
    if (selectedRow != -1) {
        // Ambil data dari baris yang diklik
        String namaWilayah = tblWilayah.getValueAt(selectedRow, 0).toString();
        String koordinat = tblWilayah.getValueAt(selectedRow, 1).toString();

        // Tampilkan di field input
        txtNamaWilayah.setText(namaWilayah);
        txtKoordinat.setText(koordinat);
    }
    }//GEN-LAST:event_tblWilayahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManajamenWilayahTangkap().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditWilayah;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambahWilayah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWilayah;
    private javax.swing.JTextField txtKoordinat;
    private javax.swing.JTextField txtNamaWilayah;
    // End of variables declaration//GEN-END:variables
}
