/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.WilayahController;
import dao.WilayahTangkapDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.WilayahTangkap;
import java.util.List; 
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import java.util.regex.Pattern;

/**
 *
 * @author rfebr
 */
public class ManajamenWilayahTangkap extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManajamenWilayahTangkap.class.getName());
    private final WilayahController controller = new WilayahController();
    private List<WilayahTangkap> currentWilayahList;


    public ManajamenWilayahTangkap() {
        initComponents();
        setLocationRelativeTo(null);
        loadTabel();
        
        DocumentFilter filter = new DocumentFilter() {
            private final Pattern regex = Pattern.compile("[0-9.,\\s-]*"); // Izinkan angka, koma, titik, spasi, minus

            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (string == null) return;
                if (regex.matcher(string).matches()) {
                    super.insertString(fb, offset, string, attr);
                }
            }
            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text == null) return;
                if (regex.matcher(text).matches()) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        };
        ((AbstractDocument) txtKoordinat.getDocument()).setDocumentFilter(filter);
        // ---
    }
    
    private void kosongkanForm() {
        txtNamaWilayah.setText("");
        txtKoordinat.setText("");
        tblWilayah.clearSelection(); 
    }

    private void loadTabel() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Nama Wilayah Tangkap", "Titik Koordinat"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.currentWilayahList = controller.getAllWilayah();
        
        for (WilayahTangkap w : this.currentWilayahList) {
            model.addRow(new Object[]{w.getNamaWilayah(), w.getKoordinat()});
        }

        tblWilayah.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWilayah = new javax.swing.JTable();
        btnEditWilayah = new javax.swing.JButton();
        btnTambahWilayah = new javax.swing.JButton();
        txtKoordinat = new javax.swing.JTextField();
        txtNamaWilayah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(52, 99, 146));
        btnKembali.setText("Kembali");
        btnKembali.setFocusPainted(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 100, 30));

        tblWilayah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblWilayah.setForeground(new java.awt.Color(52, 99, 146));
        tblWilayah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Wilayah Tangkap", "Titik Koordinat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWilayah.getTableHeader().setReorderingAllowed(false);
        tblWilayah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWilayahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblWilayah);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 360, 140));

        btnEditWilayah.setBackground(new java.awt.Color(153, 153, 153));
        btnEditWilayah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnEditWilayah.setForeground(new java.awt.Color(255, 255, 255));
        btnEditWilayah.setText("Edit");
        btnEditWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditWilayahActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditWilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 245, 90, 30));

        btnTambahWilayah.setBackground(new java.awt.Color(52, 99, 146));
        btnTambahWilayah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTambahWilayah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahWilayah.setText("Tambah");
        btnTambahWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahWilayahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambahWilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 245, 90, 30));

        txtKoordinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKoordinatActionPerformed(evt);
            }
        });
        jPanel1.add(txtKoordinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 360, 30));

        txtNamaWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaWilayahActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamaWilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 360, 30));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Titik Koordinat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Nama Wilayah Tangkap");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Wilayah Tangkap");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Manajemen");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 480, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background Pegawai.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaWilayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaWilayahActionPerformed

    private void txtKoordinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKoordinatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKoordinatActionPerformed

    private void btnEditWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditWilayahActionPerformed
        int selectedRow = tblWilayah.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        WilayahTangkap wilayah = this.currentWilayahList.get(selectedRow);

        if (wilayah != null) {
            wilayah.setNamaWilayah(txtNamaWilayah.getText());
            wilayah.setKoordinat(txtKoordinat.getText());
            
            try {
                controller.updateWilayah(wilayah); 
                JOptionPane.showMessageDialog(this, "Data wilayah berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadTabel();
                kosongkanForm();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal update: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditWilayahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahWilayahActionPerformed
        try {
            controller.tambahWilayah(txtNamaWilayah.getText(), txtKoordinat.getText());
            
            JOptionPane.showMessageDialog(this, "Wilayah baru berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadTabel();
            kosongkanForm();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambah: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            e.printStackTrace(); 
        }
    }//GEN-LAST:event_btnTambahWilayahActionPerformed

    private void tblWilayahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWilayahMouseClicked
        int selectedRow = tblWilayah.getSelectedRow();
        if (selectedRow != -1) {
            WilayahTangkap wilayah = this.currentWilayahList.get(selectedRow);
            txtNamaWilayah.setText(wilayah.getNamaWilayah());
            txtKoordinat.setText(wilayah.getKoordinat());
    }
    }//GEN-LAST:event_tblWilayahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManajamenWilayahTangkap().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditWilayah;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambahWilayah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWilayah;
    private javax.swing.JTextField txtKoordinat;
    private javax.swing.JTextField txtNamaWilayah;
    // End of variables declaration//GEN-END:variables
}
