/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PegawaiController;
import dao.KapalDAO;
import dao.NelayanDAO;
import java.awt.Desktop;
import java.net.URI;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Kapal;
import model.Nelayan;
import model.Pegawai; 
import model.enums.StatusKapal;
import model.enums.StatusNelayan;
import java.awt.Desktop;  
import java.net.URI;      
/**
 *
 * @author rfebr
 */
public class ManajemenAkunNelayan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManajemenAkunNelayan.class.getName());
    private final Pegawai pegawaiLogin;
    private final PegawaiController controller = new PegawaiController();
    private final NelayanDAO nelayanDAO = new NelayanDAO();
    private final KapalDAO kapalDAO = new KapalDAO();
    private List<Nelayan> listNelayanNonaktif;
    private List<Kapal> listKapalNonaktif;


    public ManajemenAkunNelayan(Pegawai pegawai) {
        initComponents();
        this.pegawaiLogin = pegawai;
        setLocationRelativeTo(null);   
        setTitle("Manajemen Akun - " + this.pegawaiLogin.getNama());        
        loadTblAkunNelayan();
        loadTblKapal();
    }
    private void loadTblAkunNelayan() {
        DefaultTableModel model = (DefaultTableModel) tblAkunNelayan.getModel();
        model.setRowCount(0); 
        
        this.listNelayanNonaktif = nelayanDAO.findByStatus(StatusNelayan.Nonaktif);
        
        for (Nelayan nelayan : this.listNelayanNonaktif) {
            model.addRow(new Object[]{
                nelayan.getNama(), 
                nelayan.getNib(),
                nelayan.getNoHp()   
            });
        }
    }
    
    private void loadTblKapal() {
        DefaultTableModel model = (DefaultTableModel) tblKapal.getModel();
        model.setRowCount(0); 
        
        this.listKapalNonaktif = kapalDAO.findAllByStatusAndNelayanStatus(StatusKapal.Nonaktif, StatusNelayan.Aktif);
        
        for (Kapal kapal : this.listKapalNonaktif) {
            model.addRow(new Object[]{
                kapal.getNelayan().getUsername(), 
                kapal.getNelayan().getNib(),    
                kapal.getNoRegistrasi(),
                kapal.getKategoriKapal(),
                kapal.getJenisKapal()
            });
        }
    }
    
    private Nelayan getSelectedNelayan() {
        int selectedRow = tblAkunNelayan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih akun nelayan dari tabel atas.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return this.listNelayanNonaktif.get(selectedRow);
    }
    
    private Kapal getSelectedKapal() {
        int selectedRow = tblKapal.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih kapal dari tabel bawah.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return this.listKapalNonaktif.get(selectedRow);
    }
    
    // --- METHOD HELPER: BUKA LINK DI BROWSER ---
//    private void openLinkInBrowser(String url) {
//        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
//            try {
//                // Pastikan URL valid
//                if (url == null || url.isEmpty()) {
//                    throw new Exception("URL Foto tidak ditemukan.");
//                }
//                // Tambahkan https:// jika belum ada (penting untuk Google Drive)
//                if (!url.startsWith("http://") && !url.startsWith("https://")) {
//                    url = "https://" + url;
//                }
//                Desktop.getDesktop().browse(new URI(url));
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, "Gagal membuka link: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Fitur buka browser tidak didukung di sistem ini.", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAkunNelayan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKapal = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnAccAkun = new javax.swing.JButton();
        btnTolakAkun = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnTolakKapal = new javax.swing.JButton();
        btnAccKapal = new javax.swing.JButton();
        btnOpenKapal = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 99, 146));
        jLabel1.setText("Manajemen Akun Nelayan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        tblAkunNelayan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblAkunNelayan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "NIB", "No. HP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAkunNelayan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblAkunNelayan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 410, 120));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 99, 146));
        jLabel2.setText("Daftar Akun Nelayan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        tblKapal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Username", "NIB", "No. Registrasi", "Kategori", "Jenis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKapal.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblKapal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 410, 120));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 99, 146));
        jLabel3.setText("Daftar Kapal Nelayan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, 20));

        btnAccAkun.setBackground(new java.awt.Color(0, 122, 63));
        btnAccAkun.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnAccAkun.setForeground(new java.awt.Color(255, 255, 255));
        btnAccAkun.setText("Acc");
        btnAccAkun.setBorderPainted(false);
        btnAccAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccAkunActionPerformed(evt);
            }
        });
        getContentPane().add(btnAccAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, 30));

        btnTolakAkun.setBackground(new java.awt.Color(204, 0, 0));
        btnTolakAkun.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTolakAkun.setForeground(new java.awt.Color(255, 255, 255));
        btnTolakAkun.setText("Tolak");
        btnTolakAkun.setBorderPainted(false);
        btnTolakAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTolakAkunActionPerformed(evt);
            }
        });
        getContentPane().add(btnTolakAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 100, -1, 30));

        btnKembali.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(52, 99, 146));
        btnKembali.setText("Kembali");
        btnKembali.setFocusPainted(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTolakKapal.setBackground(new java.awt.Color(204, 0, 0));
        btnTolakKapal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTolakKapal.setForeground(new java.awt.Color(255, 255, 255));
        btnTolakKapal.setText("Tolak");
        btnTolakKapal.setBorderPainted(false);
        btnTolakKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTolakKapalActionPerformed(evt);
            }
        });
        jPanel1.add(btnTolakKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, 30));

        btnAccKapal.setBackground(new java.awt.Color(0, 122, 63));
        btnAccKapal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnAccKapal.setForeground(new java.awt.Color(255, 255, 255));
        btnAccKapal.setText("Acc");
        btnAccKapal.setBorderPainted(false);
        btnAccKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccKapalActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, 30));

        btnOpenKapal.setBackground(new java.awt.Color(52, 99, 146));
        btnOpenKapal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnOpenKapal.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenKapal.setText("Open");
        btnOpenKapal.setBorderPainted(false);
        btnOpenKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenKapalActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 530, 500));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background Pegawai.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenKapalActionPerformed
      Kapal kapal = getSelectedKapal();
        if (kapal == null) return;
        
        String url = kapal.getFotoKapal();
        
        new ImageViewerDialog(this, url).setVisible(true);
    }//GEN-LAST:event_btnOpenKapalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuPegawai(this.pegawaiLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnAccAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccAkunActionPerformed
        Nelayan nelayan = getSelectedNelayan();
        if (nelayan == null) return;
        
        int response = JOptionPane.showConfirmDialog(
            this, "Yakin ingin menyetujui akun nelayan: " + nelayan.getNama() + "?",
            "Konfirmasi ACC Akun", JOptionPane.YES_NO_OPTION
        );
        
        if (response == JOptionPane.YES_OPTION) {
            try {
                controller.verifikasiAkunNelayan(nelayan);
                JOptionPane.showMessageDialog(this, "Akun " + nelayan.getNama() + " berhasil diaktifkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadTblAkunNelayan(); 
                loadTblKapal();       
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal ACC Akun: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAccAkunActionPerformed

    private void btnTolakAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakAkunActionPerformed
        Nelayan nelayan = getSelectedNelayan();
        if (nelayan == null) return;
        
        int response = JOptionPane.showConfirmDialog(
            this, "Yakin ingin MENOLAK/MENGHAPUS pendaftaran " + nelayan.getNama() + "?\nData nelayan dan kapal pertamanya akan dihapus permanen.",
            "Konfirmasi TOLAK Akun", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE
        );
        
        if (response == JOptionPane.YES_OPTION) {
            try {
                controller.tolakAkunNelayan(nelayan);
                JOptionPane.showMessageDialog(this, "Akun " + nelayan.getNama() + " berhasil ditolak dan dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadTblAkunNelayan(); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal TOLAK Akun: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTolakAkunActionPerformed

    private void btnAccKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccKapalActionPerformed
        Kapal kapal = getSelectedKapal();
        if (kapal == null) return;
        
        int response = JOptionPane.showConfirmDialog(
            this, "Yakin ingin menyetujui kapal: " + kapal.getNamaKapal() + " (" + kapal.getNoRegistrasi() + ")?",
            "Konfirmasi ACC Kapal", JOptionPane.YES_NO_OPTION
        );
        
        if (response == JOptionPane.YES_OPTION) {
            try {
                controller.verifikasiKapal(kapal);
                JOptionPane.showMessageDialog(this, "Kapal " + kapal.getNamaKapal() + " berhasil diaktifkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadTblKapal(); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal ACC Kapal: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAccKapalActionPerformed

    private void btnTolakKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakKapalActionPerformed
        Kapal kapal = getSelectedKapal();
        if (kapal == null) return;
        
        int response = JOptionPane.showConfirmDialog(
            this, "Yakin ingin MENOLAK/MENGHAPUS kapal " + kapal.getNamaKapal() + "?\nData kapal akan dihapus permanen.",
            "Konfirmasi TOLAK Kapal", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE
        );
        
        if (response == JOptionPane.YES_OPTION) {
            try {
                controller.tolakKapal(kapal);
                JOptionPane.showMessageDialog(this, "Kapal " + kapal.getNamaKapal() + " berhasil ditolak dan dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadTblKapal(); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal TOLAK Kapal: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTolakKapalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccAkun;
    private javax.swing.JButton btnAccKapal;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnOpenKapal;
    private javax.swing.JButton btnTolakAkun;
    private javax.swing.JButton btnTolakKapal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tblAkunNelayan;
    private javax.swing.JTable tblKapal;
    // End of variables declaration//GEN-END:variables
}
