/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author rfebr
 */
public class ManajemenAkunNelayan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManajemenAkunNelayan.class.getName());

    /**
     * Creates new form AccNelayan
     */
    public ManajemenAkunNelayan() {
        initComponents();
        setLocationRelativeTo(null);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnAccKapal = new javax.swing.JButton();
        btnTolakKapal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAkunNelayan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKapal = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnAccAkun = new javax.swing.JButton();
        btnTolakAkun = new javax.swing.JButton();
        btnOpenKapal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAJEMEN AKUN NELAYAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        btnKembali.setBackground(new java.awt.Color(0, 51, 102));
        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.setBorderPainted(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, 30));

        btnAccKapal.setBackground(new java.awt.Color(0, 102, 0));
        btnAccKapal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAccKapal.setForeground(new java.awt.Color(255, 255, 255));
        btnAccKapal.setText("ACC");
        btnAccKapal.setBorderPainted(false);
        getContentPane().add(btnAccKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, 30));

        btnTolakKapal.setBackground(new java.awt.Color(153, 0, 0));
        btnTolakKapal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTolakKapal.setForeground(new java.awt.Color(255, 255, 255));
        btnTolakKapal.setText("TOLAK");
        btnTolakKapal.setBorderPainted(false);
        getContentPane().add(btnTolakKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, 30));

        tblAkunNelayan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "NIB", "No. HP"
            }
        ));
        jScrollPane1.setViewportView(tblAkunNelayan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 670, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Daftar Akun Nelayan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        tblKapal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Username", "NIB", "No. Registrasi", "Kategori", "Jenis"
            }
        ));
        jScrollPane2.setViewportView(tblKapal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 670, 170));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Daftar Kapal Nelayan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));

        btnAccAkun.setBackground(new java.awt.Color(0, 102, 0));
        btnAccAkun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAccAkun.setForeground(new java.awt.Color(255, 255, 255));
        btnAccAkun.setText("ACC");
        btnAccAkun.setBorderPainted(false);
        getContentPane().add(btnAccAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, 30));

        btnTolakAkun.setBackground(new java.awt.Color(153, 0, 0));
        btnTolakAkun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTolakAkun.setForeground(new java.awt.Color(255, 255, 255));
        btnTolakAkun.setText("TOLAK");
        btnTolakAkun.setBorderPainted(false);
        getContentPane().add(btnTolakAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, 30));

        btnOpenKapal.setBackground(new java.awt.Color(0, 51, 102));
        btnOpenKapal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpenKapal.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenKapal.setText("OPEN");
        btnOpenKapal.setBorderPainted(false);
        btnOpenKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenKapalActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpenKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenKapalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenKapalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new MenuPegawai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManajemenAkunNelayan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccAkun;
    private javax.swing.JButton btnAccKapal;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnOpenKapal;
    private javax.swing.JButton btnTolakAkun;
    private javax.swing.JButton btnTolakKapal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAkunNelayan;
    private javax.swing.JTable tblKapal;
    // End of variables declaration//GEN-END:variables
}
