/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Admin;

/**
 *
 * @author rfebr
 */
public class MenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());
    private Admin adminLogin;


    /**
     * Creates new form menuPage
     */
    public MenuAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public MenuAdmin(Admin admin) {
        initComponents();
        setLocationRelativeTo(null);
        this.adminLogin = admin;
        setTitle("Menu Admin - " + admin.getNama());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnManajemenWilayah = new javax.swing.JButton();
        btnManajemenAkun = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        btnKeluar.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(52, 99, 146));
        btnKeluar.setText("Keluar");
        btnKeluar.setFocusPainted(false);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(670, 40, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo Dark.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 193, 55);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 99, 146));
        jLabel4.setText("Selamat Datang, Admin");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 110);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pilih Menu Untuk Melanjutkan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 190, 610, 90);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManajemenWilayah.setBackground(new java.awt.Color(52, 99, 146));
        btnManajemenWilayah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnManajemenWilayah.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenWilayah.setText("Manajemen Wilayah Tangkap");
        btnManajemenWilayah.setBorderPainted(false);
        btnManajemenWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManajemenWilayahActionPerformed(evt);
            }
        });
        jPanel1.add(btnManajemenWilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 240, 50));

        btnManajemenAkun.setBackground(new java.awt.Color(52, 99, 146));
        btnManajemenAkun.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnManajemenAkun.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenAkun.setText("Manajemen Akun Pegawai");
        btnManajemenAkun.setBorder(btnManajemenWilayah.getBorder());
        btnManajemenAkun.setBorderPainted(false);
        btnManajemenAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManajemenAkunActionPerformed(evt);
            }
        });
        jPanel1.add(btnManajemenAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 50));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 360, 800, 140);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background Admin.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManajemenAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManajemenAkunActionPerformed
        // TODO add your handling code here:
        new ManajemenAkunPegawai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManajemenAkunActionPerformed

    private void btnManajemenWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManajemenWilayahActionPerformed
        // TODO add your handling code here:
        new ManajamenWilayahTangkap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManajemenWilayahActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new LandingPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnManajemenAkun;
    private javax.swing.JButton btnManajemenWilayah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
