/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.UserController;
import javax.swing.JOptionPane;
import model.User;
/**
 *
 * @author rfebr
 */
public class MenuUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUser.class.getName());
    private User userLogin;

    /**
     * Creates new form menuPage
     */
    public MenuUser() {
        initComponents();
        setLocationRelativeTo(null);

    }
        public MenuUser(User user) {
        initComponents();
        setLocationRelativeTo(null);
        this.userLogin = user;
        setTitle("Menu Pengguna - " + user.getNama());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPengaduan = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnProfil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        btnPengaduan.setBackground(new java.awt.Color(0, 51, 102));
        btnPengaduan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPengaduan.setForeground(new java.awt.Color(255, 255, 255));
        btnPengaduan.setText("Buat Pengaduan");
        btnPengaduan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPengaduan.setBorderPainted(false);
        btnPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengaduanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengaduan);
        btnPengaduan.setBounds(220, 230, 370, 36);

        btnDaftar.setBackground(new java.awt.Color(0, 51, 102));
        btnDaftar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar.setText("Daftar Sebagai Nelayan");
        btnDaftar.setBorderPainted(false);
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDaftar);
        btnDaftar.setBounds(220, 290, 370, 36);

        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(0, 51, 102));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(680, 30, 90, 30);

        btnProfil.setBackground(new java.awt.Color(0, 51, 102));
        btnProfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProfil.setForeground(new java.awt.Color(255, 255, 255));
        btnProfil.setText("Profil");
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfil);
        btnProfil.setBounds(580, 30, 84, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PILIH MENU UNTUK MELANJUTKAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 120, 440, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 193, 55);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengaduanActionPerformed
        // TODO add your handling code here:
        new LaporanPengaduan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPengaduanActionPerformed

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
        // TODO add your handling code here:
        new ProfilUser(userLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new LandingPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
        UserController userController = new UserController();
        if (userController.sudahDaftarNelayan(userLogin.getUserId())) {
            JOptionPane.showMessageDialog(this, 
                "Anda sudah mendaftar sebagai nelayan.\nMohon tunggu untuk diproses.",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
    } else {
            new SignUpNelayan(userLogin).setVisible(true);
            this.dispose();
    }
    
    }//GEN-LAST:event_btnDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPengaduan;
    private javax.swing.JButton btnProfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
