/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Nelayan;


/**
 *
 * @author Tuf
 */
public class MenuNelayan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuNelayan.class.getName());
    private Nelayan nelayanLogin;

    /**
     * Creates new form menuPage
     */
    public MenuNelayan() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public MenuNelayan(Nelayan nelayan) {
        initComponents();
        setLocationRelativeTo(null);
        this.nelayanLogin = nelayan;
        setTitle("Menu Nelayan - " + nelayan.getNama());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPengaduan = new javax.swing.JButton();
        btnPenangkapan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnProfil = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pilih Menu Untuk Melanjutkan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 190, 560, 90);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPengaduan.setBackground(new java.awt.Color(52, 99, 146));
        btnPengaduan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnPengaduan.setForeground(new java.awt.Color(255, 255, 255));
        btnPengaduan.setText("Buat Pengaduan");
        btnPengaduan.setBorder(btnPenangkapan.getBorder());
        btnPengaduan.setBorderPainted(false);
        btnPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengaduanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 50));

        btnPenangkapan.setBackground(new java.awt.Color(52, 99, 146));
        btnPenangkapan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnPenangkapan.setForeground(new java.awt.Color(255, 255, 255));
        btnPenangkapan.setText("Buat Laporan Penangkapan");
        btnPenangkapan.setBorderPainted(false);
        btnPenangkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenangkapanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPenangkapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 240, 50));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 360, 800, 140);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo Dark.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnProfil.setBackground(new java.awt.Color(52, 99, 146));
        btnProfil.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnProfil.setForeground(new java.awt.Color(255, 255, 255));
        btnProfil.setText("Profil");
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });
        jPanel2.add(btnProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 84, 30));

        btnKeluar.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(52, 99, 146));
        btnKeluar.setText("Keluar");
        btnKeluar.setFocusPainted(false);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 84, 30));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 99, 146));
        jLabel4.setText("Selamat Datang, Nelayan");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 110);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background Nelayan.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengaduanActionPerformed
        // TODO add your handling code here:
        new FormLaporanPengaduan(nelayanLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPengaduanActionPerformed

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
        // TODO add your handling code here:
        new ProfilNelayan(nelayanLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnPenangkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenangkapanActionPerformed
        // TODO add your handling code here:
        new LaporanPenangkapan(this.nelayanLogin).setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnPenangkapanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new LandingPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuNelayan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPenangkapan;
    private javax.swing.JButton btnPengaduan;
    private javax.swing.JButton btnProfil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
