/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Admin;

/**
 *
 * @author rfebr
 */
public class MenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());
    private Admin adminLogin;


    /**
     * Creates new form menuPage
     */
    public MenuAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public MenuAdmin(Admin admin) {
        initComponents();
        setLocationRelativeTo(null);
        this.adminLogin = admin;
        setTitle("Menu Admin - " + admin.getNama());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManajemenAkun = new javax.swing.JButton();
        btnManajemenWilayah = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        btnManajemenAkun.setBackground(new java.awt.Color(0, 51, 102));
        btnManajemenAkun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManajemenAkun.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenAkun.setText("Manajemen Akun Pegawai");
        btnManajemenAkun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnManajemenAkun.setBorderPainted(false);
        btnManajemenAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManajemenAkunActionPerformed(evt);
            }
        });
        getContentPane().add(btnManajemenAkun);
        btnManajemenAkun.setBounds(220, 230, 370, 36);

        btnManajemenWilayah.setBackground(new java.awt.Color(0, 51, 102));
        btnManajemenWilayah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManajemenWilayah.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenWilayah.setText("Manajemen Wilayah Tangkap");
        btnManajemenWilayah.setBorderPainted(false);
        btnManajemenWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManajemenWilayahActionPerformed(evt);
            }
        });
        getContentPane().add(btnManajemenWilayah);
        btnManajemenWilayah.setBounds(220, 290, 370, 36);

        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(0, 51, 102));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(680, 30, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PILIH MENU UNTUK MELANJUTKAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 120, 440, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 193, 55);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManajemenAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManajemenAkunActionPerformed
        // TODO add your handling code here:
        new ManajemenAkunPegawai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManajemenAkunActionPerformed

    private void btnManajemenWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManajemenWilayahActionPerformed
        // TODO add your handling code here:
        new ManajamenWilayahTangkap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManajemenWilayahActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new LandingPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnManajemenAkun;
    private javax.swing.JButton btnManajemenWilayah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
