/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.UserController;
import dao.NelayanDAO;
import model.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Kapal;
import org.mindrot.jbcrypt.BCrypt;
import model.Nelayan;
import model.enums.StatusKapal;
/**
 *
 * @author rfebr
 */
public class ProfilNelayan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfilNelayan.class.getName());
    private Nelayan nelayanLogin;
    private final UserController userController = new UserController();


    /**
     * Creates new form nelayanProfile
     */
        public ProfilNelayan(Nelayan nelayanLogin) {
            initComponents();
            this.nelayanLogin = nelayanLogin;
            setLocationRelativeTo(null);
            loadData();
            loadTableKapal(nelayanLogin);
        }
        
        private void loadData() {
            if (nelayanLogin != null) {
                txtNama.setText(nelayanLogin.getNama());
                txtUsername.setText(nelayanLogin.getUsername());
                txtEmail.setText(nelayanLogin.getEmail());
                txtHP.setText(nelayanLogin.getNoHp());
                txtAlamat.setText(nelayanLogin.getAlamat());
                txtNIB.setText(nelayanLogin.getNib() != null ? nelayanLogin.getNib().toString() : "");
                txtNIB.setEditable(false); // ga bisa diubah
                jPasswordField1.setText("");
            }
        }
        private void updateProfil() {
            String nama = txtNama.getText().trim();
            String username = txtUsername.getText().trim();
            String email = txtEmail.getText().trim();
            String noHp = txtHP.getText().trim();
            String alamat = txtAlamat.getText().trim();
            String newPassword = new String(jPasswordField1.getPassword()).trim();

            Nelayan tempNelayan = new Nelayan();
            tempNelayan.setUserId(nelayanLogin.getUserId());
            tempNelayan.setNama(nama);
            tempNelayan.setUsername(username);
            tempNelayan.setEmail(email);
            tempNelayan.setNoHp(noHp);
            tempNelayan.setAlamat(alamat);
            tempNelayan.setNib(nelayanLogin.getNib()); // nib ga boleh diubah
            tempNelayan.setRole(nelayanLogin.getRole()); // jaga role

            if (!newPassword.isEmpty()) {
                String hashed = BCrypt.hashpw(newPassword, BCrypt.gensalt());
                tempNelayan.setPassword(hashed);
            } else {
                tempNelayan.setPassword(nelayanLogin.getPassword());
            }

            boolean success = userController.updateProfil(tempNelayan);

            if (success) {
                JOptionPane.showMessageDialog(this, "Profil berhasil diperbarui!");
                this.nelayanLogin = tempNelayan;
                jPasswordField1.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui profil! Username sudah dipakai.");
                loadData();
            }
        }
        
 private void loadTableKapal(Nelayan nelayanLogin) {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"No. Registrasi", "Nama Kapal", "Jenis Kapal"}, 0
    );
    tblKapal.setModel(model);

    NelayanDAO nelayanDAO = new NelayanDAO();
    Nelayan nelayan = nelayanDAO.findById(nelayanLogin.getUserId());

    if (nelayan != null && nelayan.getDaftarKapal() != null) {
        for (Kapal kapal : nelayan.getDaftarKapal()) {
            if (kapal.getStatusKapal() == StatusKapal.Aktif) {
                model.addRow(new Object[]{
                    kapal.getNoRegistrasi(),
                    kapal.getNamaKapal(),
                    kapal.getJenisKapal()
                });
            }
        }
    }
}


        

       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNIB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblKapal = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        btnHapusKapal = new javax.swing.JButton();
        btnTambahKapal = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jScrollPane6.setViewportView(txtAlamat);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 280, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No. Handphone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        txtHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHPActionPerformed(evt);
            }
        });
        getContentPane().add(txtHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 280, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 280, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 40, 20));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 280, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 20));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 280, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, 20));

        txtNIB.setEditable(false);
        getContentPane().add(txtNIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 280, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIB");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(0, 51, 102));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setBorderPainted(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 120, 30));

        tblKapal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No. Registrasi", "Nama Kapal", "Jenis Kapal"
            }
        ));
        jScrollPane8.setViewportView(tblKapal);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 470, 140));

        btnKembali.setBackground(new java.awt.Color(0, 51, 102));
        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.setBorderPainted(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, 30));

        btnHapusKapal.setBackground(new java.awt.Color(102, 0, 0));
        btnHapusKapal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapusKapal.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusKapal.setText("Hapus Kapal");
        btnHapusKapal.setBorderPainted(false);
        btnHapusKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKapalActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapusKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 120, 30));

        btnTambahKapal.setBackground(new java.awt.Color(0, 51, 102));
        btnTambahKapal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambahKapal.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahKapal.setText("Tambah Kapal");
        btnTambahKapal.setBorderPainted(false);
        btnTambahKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKapalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 120, 30));

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("PROFIL");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 280, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new MenuNelayan(nelayanLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnHapusKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKapalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusKapalActionPerformed

    private void btnTambahKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKapalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahKapalActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
            updateProfil();

    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnHapusKapal;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahKapal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tblKapal;
    private javax.swing.JLabel title;
    private javax.swing.JTextPane txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtNIB;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
