/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import jnafilechooser.api.JnaFileChooser;
import model.User;

/**
 *
 * @author rfebr
 */

public class SignUpNelayan extends javax.swing.JFrame {
        private String selectedImagePath;  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpNelayan.class.getName());
    private User currentUser;

    /**
     * Creates new form signUpNelayanPage
     */
    public SignUpNelayan(User user) {
        initComponents();
        this.currentUser = user;
        lblPreview.setVisible(false);
        setLocationRelativeTo(null);
        dropKategori.removeAllItems();
        dropKategori.addItem("Pilih Kategori");
        dropKategori.addItem("Kapal Besar");
        dropKategori.addItem("Kapal Sedang");
        dropKategori.addItem("Kapal Kecil");

        dropJenisKapal.removeAllItems();
        dropJenisKapal.addItem("Pilih Jenis Kapal");

        dropKategori.addItemListener(e -> {
            if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                updateJenisKapal((String) e.getItem());
            }
        });
    }   
    
    private void updateJenisKapal(String kategori) {
    dropJenisKapal.removeAllItems();

    if (kategori == null || kategori.equals("Pilih Kategori")) {
        dropJenisKapal.addItem("Pilih Jenis Kapal");
        return;
    }

    switch (kategori) {
        case "Kapal Besar" -> {
            dropJenisKapal.addItem("Purse Seine Besar");
            dropJenisKapal.addItem("Trawl Laut Dalam");
        }
        case "Kapal Sedang" -> {
            dropJenisKapal.addItem("Cantrang");
            dropJenisKapal.addItem("Purse Seine (Cincin)");
            dropJenisKapal.addItem("Longline (Rawai Tuna)");
            dropJenisKapal.addItem("Bagang Kapal");
        }
        case "Kapal Kecil" -> {
            dropJenisKapal.addItem("Jukung");
            dropJenisKapal.addItem("Katir");
            dropJenisKapal.addItem("Sampan");
            dropJenisKapal.addItem("Perahu Motor Tempel");
            dropJenisKapal.addItem("Gillnet (Jaring Insang)");
            dropJenisKapal.addItem("Bagang Apung/Tancap");
        }
        default -> dropJenisKapal.addItem("Pilih Jenis Kapal");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNIB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNoRegistrasi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaKapal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dropJenisKapal = new javax.swing.JComboBox<>();
        dropKategori = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        lblPreview = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("NIB");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));
        getContentPane().add(txtNIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 310, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("No. Registrasi Kapal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));
        getContentPane().add(txtNoRegistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 310, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Nama Kapal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        txtNamaKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKapalActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 310, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Jenis Kapal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Kategori");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Foto Kapal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        btnUpload.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpload.setForeground(new java.awt.Color(0, 51, 102));
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 395, 80, 30));

        btnSubmit.setBackground(new java.awt.Color(0, 51, 102));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 310, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("DAFTAR SEBAGAI NELAYAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        dropJenisKapal.setForeground(new java.awt.Color(0, 51, 102));
        dropJenisKapal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropJenisKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropJenisKapalActionPerformed(evt);
            }
        });
        getContentPane().add(dropJenisKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 310, 30));

        dropKategori.setForeground(new java.awt.Color(0, 51, 102));
        dropKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(dropKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 310, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 51, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 80, 30));

        lblPreview.setText("jLabel7");
        jPanel1.add(lblPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 470, 500));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sign up.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 420, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKapalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKapalActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
    JnaFileChooser fileChooser = new JnaFileChooser();
    
    fileChooser.setTitle("Pilih Foto Kapal");
    
    fileChooser.addFilter("Gambar (*.jpg, *.png, *.jpeg)", "jpg", "png", "jpeg");
    
    boolean result = fileChooser.showOpenDialog(this);

    if (result) { // True jika file dipilih
        File selectedFile = fileChooser.getSelectedFile();
        
        if (selectedFile != null) {
            selectedImagePath = selectedFile.getAbsolutePath();

            lblPreview.setText("File terpilih: " + selectedFile.getName());
            lblPreview.setVisible(true);
        }
    }
    
        
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new MenuUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dropKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropKategoriActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dropKategoriActionPerformed

    private void dropJenisKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropJenisKapalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropJenisKapalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> dropJenisKapal;
    private javax.swing.JComboBox<String> dropKategori;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JTextField txtNIB;
    private javax.swing.JTextField txtNamaKapal;
    private javax.swing.JTextField txtNoRegistrasi;
    // End of variables declaration//GEN-END:variables
}
