/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author rfebr
 */
public class VerifikasiLaporanPengaduan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerifikasiLaporanPengaduan.class.getName());

    /**
     * Creates new form verifikasiLaporanPengaduan
     */
    public VerifikasiLaporanPengaduan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPengaduan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPenangkapan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnOpenPenangkapan = new javax.swing.JButton();
        btnOpenPengaduan = new javax.swing.JButton();
        filterPenangkapan = new javax.swing.JComboBox<>();
        filterPengaduan = new javax.swing.JComboBox<>();
        btnRefreshPenangkapan = new javax.swing.JButton();
        btnRefreshPengaduan = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPengaduan.setForeground(new java.awt.Color(0, 51, 102));
        tblPengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal Pengaduan", "Jenis Pengaduan", "Deskripsi", "Titik Koordinat", "Status", "Catatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPengaduan.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblPengaduan);
        tblPengaduan.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 700, 140));

        tblPenangkapan.setForeground(new java.awt.Color(0, 51, 102));
        tblPenangkapan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Waktu Berangkat", "Nama Pelabuhan", "Waktu Berlabuh", "Titik Koordinat", "Alat Tangkap", "Status", "Catatan "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPenangkapan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 700, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VERIFIKASI LAPORAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAPORAN PENGADUAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LAPORAN PENANGKAPAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        btnKembali.setBackground(new java.awt.Color(0, 51, 102));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.setBorderPainted(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 100, 30));

        btnOpenPenangkapan.setBackground(new java.awt.Color(0, 51, 102));
        btnOpenPenangkapan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpenPenangkapan.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenPenangkapan.setText("OPEN");
        btnOpenPenangkapan.setBorderPainted(false);
        btnOpenPenangkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPenangkapanActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpenPenangkapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, 30));

        btnOpenPengaduan.setBackground(new java.awt.Color(0, 51, 102));
        btnOpenPengaduan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpenPengaduan.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenPengaduan.setText("OPEN");
        btnOpenPengaduan.setBorderPainted(false);
        btnOpenPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPengaduanActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpenPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, 30));

        filterPenangkapan.setForeground(new java.awt.Color(0, 51, 102));
        filterPenangkapan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(filterPenangkapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 140, 30));

        filterPengaduan.setForeground(new java.awt.Color(0, 51, 102));
        filterPengaduan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(filterPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 150, 30));

        btnRefreshPenangkapan.setBackground(new java.awt.Color(0, 51, 102));
        btnRefreshPenangkapan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefreshPenangkapan.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshPenangkapan.setText("SEGARKAN");
        btnRefreshPenangkapan.setBorderPainted(false);
        btnRefreshPenangkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshPenangkapanActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefreshPenangkapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 100, 30));

        btnRefreshPengaduan.setBackground(new java.awt.Color(0, 51, 102));
        btnRefreshPengaduan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefreshPengaduan.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshPengaduan.setText("SEGARKAN");
        btnRefreshPengaduan.setBorderPainted(false);
        btnRefreshPengaduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshPengaduanActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefreshPengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 100, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new MenuPegawai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnOpenPenangkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPenangkapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenPenangkapanActionPerformed

    private void btnOpenPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPengaduanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenPengaduanActionPerformed

    private void btnRefreshPenangkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshPenangkapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshPenangkapanActionPerformed

    private void btnRefreshPengaduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshPengaduanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshPengaduanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VerifikasiLaporanPengaduan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnOpenPenangkapan;
    private javax.swing.JButton btnOpenPengaduan;
    private javax.swing.JButton btnRefreshPenangkapan;
    private javax.swing.JButton btnRefreshPengaduan;
    private javax.swing.JComboBox<String> filterPenangkapan;
    private javax.swing.JComboBox<String> filterPengaduan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPenangkapan;
    private javax.swing.JTable tblPengaduan;
    // End of variables declaration//GEN-END:variables
}
